# Generated by Django 6.0.3 on 2026-03-17 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('ARQ', 'Arquero'), ('DEF', 'Defensor'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], default='MED', max_length=3)),
                ('skill', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
