# Generated by Django 6.0.3 on 2026-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cancha_Libre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorPosicion',
            fields=[
                ('pk', models.CompositePrimaryKey('id_j', 'id_pos', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Jugador_Posicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id_pos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Posicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolPos',
            fields=[
                ('id_rol_pos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'rol_pos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('sexo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPosicion',
            fields=[
                ('pk', models.CompositePrimaryKey('id_u', 'id_pos', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Usuario_Posicion',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'managed': False},
        ),
    ]
