# Generated by Django 6.0.3 on 2026-03-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cancha_Libre', '0002_jugadorposicion_posicion_rolpos_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jugador',
            table='Jugador',
        ),
    ]
